language: php
php:
  - 7.2.0
script: skip
before_deploy:
  - bash ./scripts/build.sh
deploy:
  provider: releases
  api_key:
    secure: eQkIti5xinzEw1e0rBTDmaBrQUQcFu4brqp/CSRcRqd3Mohu6YsFs83YUXFguVWBUAfnMFFAx/7BeoToReVg4oTkev1x8u+VTxAILjTe6DGJ9oe4s24XfbDr58EbS3hTdsZylcJeXuvGi8+XxF1SBzqTf6LWiLQeSnZavKftzcgJP/AvQqWBDsXuMrrqsuI3QrKfw9Zb9CiyWqcEytxBpjEB2pvR1hjQuzz9czDvXn/wng3O1gR2WnaWY+h1Qhfa0reja0JpDHJJggwe8aFWgVlGoIY4LAE/N6b2HK0RyyPhgYquv1tA3Rl4cW4JqPa197QKBB0kmq2+mjEx1L6h4YBK0DH+m+X64CdWJ++6gqQ7SNghQuRjVBi3UrwoYNXctMhgnW2pRoMQX6hRR+1FSFDB0FZy4yQdR5JEJM9Hvxhx6jyrdW5qiXwF1Yss22Lh7G+uuivGRrLK2ioTUNe/00+li/ADJ0nikaQkB/S/dTFurWDuU0PbaUgnZFLSMw/I1uNzNWfDlV4sbnbZ5touCInB6+3CpNLWc+JCceQbHnYpZdv/WTtXt53PhGj0vHIywOndpb2DWlOPs4Di5F/3hhCYoTSUiGmieGAVpkaK0fE1yyfzhMsMzFWHUt+niTVQNppa1vmn1HpajxbZ0spIym2tbYLg/sMwlJX8OFACCIM=
  file: "./dist/paynow.zip"
  skip_cleanup: true
  on:
    repo: pay-now/paynow-prestashop
    branch: master
    tags: true