language: php
php:
  - 7.2.0
script: skip
before_deploy:
  - bash ./scripts/build.sh
deploy:
  provider: releases
  api_key:
    secure: p4GztatZLACqsNoofyrMeDtSDWYC8DqHYl0T5owfexlpjlQHsW2DvYJtDN+TxJpAdHNp5dsqC1TXagpqLQsf4CfJOUSlHd5Lyhz53wBeDbKPXKWioHYBryeR3oNq/nZcmkJE8g3OhT0f6DEWX63RENMLWpLKbZdSJ75uZnS55j4mjGN9v2X3FXKiSZBmG8XK0GJvwTTQkr1cHzYBO5Xv+HztLKDR5JAmOxBq7RQ8Pdp/Mld6QU2SXNnLBka2dPphTzDF9vpNyLheJh4ZK/X6Mp6bO9jGQXanme6K/8AIqggCuC/elxFeI8GQL4dzZ2Z1DHHABdY2kqP9uCooRyVzdyBdc6zKJwtIZglahMku/u8KCWPXj+il8C/V+43zh0v4/6joIUVnw8Ut5drVdMR1eTZvNunTTDw9+gue0Fzdnt1cQE0GA8EiZmJo4RlK1gYRsPiv1KfNcbRBdM+mdZpWffkOArpaW8lL4Hg3f7+wIwGRiwucNTch2R1WUM7OeImynNqnXPXF/bf0GvTG9kZQwfDlrTHMEwBPpZnGyCvIgxxvhqT7dA+11wxFtEPf8UUfG8DFN88MUWaT/BQbCCK697/BCLlu8BzBWVkvDeCp9ivG3U11V4situ4Zb453d4R1+sniRcXtuA3sqo8NJScLlabASOC+irXO2JGID//k0xA=
  file: "./dist/paynow.zip"
  skip_cleanup: true
  on:
    repo: pay-now/paynow-prestashop
    branch: master
    tags: true